POST  http://localhost:3333/events
Content-Type: application/json

{
  "title": "New event",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/46b4ed6c-dd1e-45d3-ac51-ab38ddcc4587/attendees
Content-Type: application/json

{
  "name": "Kaue Alves",
  "email": "email2@example.com"
}

###

GET http://localhost:3333/events/46b4ed6c-dd1e-45d3-ac51-ab38ddcc4587

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/3/check-in

###

GET http://localhost:3333/events/46b4ed6c-dd1e-45d3-ac51-ab38ddcc4587/attendees